package:
  name: osqp
  version: "0.4.0"

source:
  git_url: https://github.com/oxfordcontrol/osqp-python.git
  git_rev: v0.4.0


requirements:
  build:
    - python
    - setuptools
    - future
    - numpy >=1.7
    - scipy >=0.13.2

  run:
    - python
    - future
    - numpy >=1.7
    - scipy >=0.13.2

test:
  # Python imports
  imports:
    - osqp
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs osqp

about:
  home: https://osqp.org
  license: Apache 2.0
  license_file: LICENSE
  summary: 'OSQP: The Operator Splitting QP Solver'
